### ISSUE TITLE
Issues passing arguments

### ISSUE THREAD

**Issue by christianmagill** [vijayhardaha/select2-Sortable#1]
Thanks for creating this!

I'm having an issue passing arguments. 

If I do something like this...

```
$select.select2Sortable({
   placeholder: 'Search...',
})
```

Then the options array after merging with the defaults winds up with a 0 item containing my settings rather than merging the values.

<img width="656" alt="Screenshot 2020-05-04 23 22 59" src="https://user-images.githubusercontent.com/2133370/81032541-3e35ba80-8e5e-11ea-90df-447f5e05e58d.png">

**Comment by vijayhardaha** [comment]
@christianmagill Please check the updated code, I have fixed the issue.
